name: "Contexts"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  print-event-name:
    name: "Print Event Name"
    runs-on: ubuntu-latest
    steps:

      - name: "Print Event Name without env"
        shell: bash
        run: |
          echo "${{ github.event.pull_request.title }}"; ls

      - name: "Print Event Name with env"
        shell: bash
        env:
          EVENT_NAME: ${{ github.event.pull_request.title }}
        run: |
          echo "${EVENT_NAME}"
          ls
          echo "123" >> 456.txt
          ls


