name: "Example simple"

on:
  pull_request:

jobs:

  print-hello:
    name: "Print Hello"
    runs-on: ubuntu-latest
    steps:

      - name: "Print Hello"
        shell: bash
        run: echo "Hello, world!"

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Git status"
        shell: bash
        run: git status