name: "Example permissions"

on:
  push:
    branches:
      - "permissions"

jobs:
  with-default-permissions:
    name: "Job with default permissions"
    runs-on: ubuntu-latest
    steps:
      # The checkout action uses github token by default to attempt to clone the repository
      # i.e.
      # with:
      #   token: ${{ github.token }}
      - name: "Checkout"
        uses: actions/checkout@v4

  with-bracket-permissions:
    name: "Job with {} permissions"
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

  with-none-permissions:
    name: "Job with contents none permissions"
    runs-on: ubuntu-latest
    permissions:
      contents: none
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

  with-read-permissions:
    name: "Job with contents read permissions"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4