name: "Example one"

on:
  push:
    branches:
      - "**"

jobs:
  print-hello:
    name: "Print Hello"
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello"
        shell: bash
        run: echo "Hello, world!"