name: "TODO"

on:
  push:
    branches:
      - "develop"

jobs:
  print-hello:
    name: "Print Hello"
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello"
        shell: bash
        run: echo "Hello, world!"