name: "Scheduling a job"

on:
  schedule:
    - cron: "16 30 22 5 *"

jobs:
  print-hello:
    name: "Print Time"
    runs-on: ubuntu-latest
    steps:
      - name: "Print current time"
        shell: bash
        run: echo $(date)
