name: "Workflow Triggered on Release"

on:
  release:
    types:
      - created

jobs:
  print-tag-name:
    name: "Print Tag Name"
    runs-on: ubuntu-latest
    steps:
      - name: "Print Tag Name"
        shell: bash
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: echo "$RELEASE_TAG was created!"