name: "IOS CI Example"

on:
  push:
    branches:
      - "ios-ci"

jobs:
  unit-tests:
    name: "Run unit tests"
    runs-on: macos-14
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - name: "Checkout ${{ github.ref }} in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Setup Xcode version."
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.3"

      - name: "Run unit tests."
        env:
          NSUnbufferedIO: "YES"
        run: >
          xcodebuild test
          -resultBundlePath './TestResults/TestResults.xcresult'
          -scheme 'Example'
          -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.4'
          -enableCodeCoverage YES

      - name: "Upload 'Test Coverage Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: "Test Coverage Results"
          if-no-files-found: error
          path: TestResults
